---
title: "EDA da Câmara"
output: 
  html_notebook: 
    theme: united
---

```{r}
library(readr)
library(dplyr, warn.conflicts = F)
library(ggplot2)
library(tidyr)
```

# Passeio nos dados da Câmara Federal

Os dados vem de [https://github.com/nazareno/dados-da-camara-federal].

```{r}
proposicoes = read_csv("https://raw.githubusercontent.com/nazareno/dados-da-camara-federal/master/dados/proposicoes.csv", 
                       col_types = cols(
                         .default = col_character(),
                         numero = col_integer(),
                         ano = col_integer()))
```

Repare que `col_types` nos dá uma maneira de especificar os tipos das colunas que serão lidos. Por exemplo, quero os ids das proposições como `character`, e não como inteiros, que seria o que ele adivinharia sem o parâmetro. 


```{r}
glimpse(proposicoes)
```

## De quando são as proposições votadas?

```{r}
anos = proposicoes %>% 
  group_by(ano) %>% 
  summarise(quantas = n())

anos %>% 
  ggplot(aes(x = ano, y = quantas)) + 
  geom_bar(fill = "white", colour = "black", stat = "identity")

# daria no mesmo fazer
# proposicoes %>% 
#   ggplot(mapping = aes(x = ano)) + 
#   geom_bar(stat = "count")
```



## Categorias de proposições

```{r}
temas = proposicoes %>% 
  filter(!is.na(tema)) %>% 
  separate_rows(tema, sep = ";")  %>% 
  mutate(tema = trimws(tema))

contagem_temas = temas %>% 
  group_by(tema) %>% 
  summarise(quantos = n()) %>% 
  arrange(-quantos)

contagem_temas %>% 
  ggplot(aes(x = reorder(tema, quantos), y = quantos)) + 
  geom_point() + 
  coord_flip()

mais_comuns = contagem_temas %>% 
  select(tema) %>% 
  slice(1:5)

temas %>% 
  filter(tema %in% mais_comuns$tema) %>% 
  ggplot(aes(x = ano)) + 
  geom_bar() + 
  facet_grid(tema ~ .)

temas %>% 
  filter(tema %in% mais_comuns$tema) %>% 
  mutate(idade = 2017 - ano) %>% 
  ggplot(aes(x = reorder(tema, idade, FUN = median), y = idade)) + 
  geom_violin() + 
  geom_point(position = position_jitter(width = .1), alpha= .5) + 
  coord_flip()
```

