---
title: "Mais sobre visualizações"
output: html_notebook
---

```{r}
library(tidyverse, warn.conflicts = F)
theme_set(theme_bw())
```

Retomaremos os dados de alunos

```{r}
dados = read_csv("dados//Dados de alunos para as aulas de FPCC-report.csv") %>% 
  select(curso = `De que curso você é aluno?`, 
         sexo = `Você é...`, 
         altura = `Qual a sua altura em centímetros?`,
         repositorios = `Em quantos repositórios de software você lembra ter contribuído nos últimos 2 anos?`, 
         linguagens = `Em quantas linguagens de programação você se considera fluente?`,
         projetos_de_pesquisa = `Em quantos projetos de pesquisa você lembra ter participado?`, 
         confianca_estatistica = `Qual seu nível de confiança hoje no uso de métodos estatísticos para analisar o resultado de um experimento?`, 
         gosta_de_forms = `O quanto você gosta de formulários online? (Obrigado por ter respondido este!)`,
         submissao = `Submit Date (UTC)`,
         fpcc2 = `Você já cursou, está cursando ou não cursou FPCC 2?`)

# Remove NAs
dados = dados %>% 
  filter(complete.cases(dados))

glimpse(dados)
```

## Um valor

```{r}
dados %>% 
  ggplot(aes(x = "Alunos", y = altura)) + 
  geom_point(size = 2, alpha = .6)
```

## Uma chave, um valor

```{r}
dados %>% 
  ggplot(aes(x = curso, y = projetos_de_pesquisa)) + 
  #geom_jitter(width = .05, height = 0, alpha = .6)
  geom_count()

dados %>% 
  ggplot(aes(x = curso)) + 
  geom_bar()

```

## 2 chaves

```{r}
dados %>% 
  ggplot(aes(x = curso, y = fpcc2)) + 
  geom_count()

dados %>% 
  ggplot(aes(x = curso, y = fpcc2, fill = confianca_estatistica)) + 
  geom_tile()

confiancas = dados %>% 
  group_by(curso, fpcc2) %>% 
  summarise(confianca_estatistica = mean(confianca_estatistica)) %>% 
  mutate(fpcc2 = factor(fpcc2, 
                           levels = c("Já cursei", 
                                      "Estou cursando em 2017", 
                                      "Estou cursando em 2016", 
                                      "Não cursei e não estou cursando"))) 
confiancas %>%
  ggplot(aes(x = curso, 
             y = fpcc2, 
             fill = confianca_estatistica)) + 
  geom_tile()
```

## Mais formas de usar o espaço

```{r}
confiancas %>%
  ggplot(aes(x = curso, 
             y = confianca_estatistica)) + 
  geom_col() + 
  facet_grid(. ~ fpcc2)

confiancas %>%
  ggplot(aes(x = fpcc2, 
             y = confianca_estatistica)) + 
  geom_col() + 
  facet_grid(. ~ curso)

confiancas %>%
  ggplot(aes(x = fpcc2, 
             y = confianca_estatistica, 
             fill = curso)) + 
  geom_col(position = "dodge") 

confiancas %>%
  ggplot(aes(x = fpcc2, 
             y = confianca_estatistica, 
             colour = curso)) + 
  geom_point(size = 3, alpha = .7) 

```

## Dispersão

Dados do Github

```{r}
ler_github_wide = function(file, min_repos = 100){
  d = read_csv(file, 
           col_types = cols(  repository_language = col_character(),
                              type = col_character(),
                              active_repos_by_url = col_integer(),
                              events = col_integer(),
                              year = col_integer(),
                              quarter = col_integer()
           )) %>% 
    filter(active_repos_by_url >= min_repos) %>% 
    mutate(events = events / active_repos_by_url) %>% 
    filter(year == 2014, quarter == 1, type != "CreateEvent") %>% 
    select(-year, -quarter, -active_repos_by_url) 

  dw <- d %>% spread(key = type, value = events)
  dw <- filter(dw, complete.cases(dw))
  return(dw)
}
  
  
github = ler_github_wide("dados/atividade-no-github-archive-2012-2015.csv")
glimpse(github)
```

```{r}
github %>% 
  ggplot(aes(x = ForkEvent, y = PushEvent)) + 
  geom_point()

github %>% 
  ggplot(aes(x = IssuesEvent, y = PushEvent, label = repository_language)) + 
  geom_point() +
  #geom_text() + 
  geom_abline(slope = 1, intercept = 0, colour = "blue") + 
  geom_abline(slope = 2, intercept = 0, colour = "darkblue") 
```

## Series temporais

```{r}
ler_github_long = function(file, min_repos = 100){
  d = read_csv(file, 
           col_types = cols(  repository_language = col_character(),
                              type = col_character(),
                              active_repos_by_url = col_integer(),
                              events = col_integer(),
                              year = col_integer(),
                              quarter = col_integer()
           )) %>% 
    filter(active_repos_by_url >= min_repos, 
           type != "CreateEvent", 
           year < 2015) %>% 
    mutate(events = events / active_repos_by_url, 
           time = lubridate::ymd(paste(year, 1 + quarter*3, 1, sep="-"))) 

  return(d)
}
  
  
github_l = ler_github_long("dados/atividade-no-github-archive-2012-2015.csv", min_repos = 1) %>% 
  filter(repository_language %in% c("Scala", "Java", "JavaScript", "Go", "C", "C++"))
glimpse(github_l)

```

```{r}
github_l %>% 
  filter(type == "PushEvent", time > lubridate::ymd("2013-01-01")) %>% 
  ggplot(aes(x = time, y = events, colour = repository_language)) + 
  geom_line()
  
github_l %>% 
  filter(type == "PushEvent", time > lubridate::ymd("2013-01-01")) %>% 
  ggplot(aes(x = time, y = events, colour = repository_language)) + 
  geom_line() + 
  facet_grid(. ~ repository_language)

github_l %>% 
  filter(time > lubridate::ymd("2013-01-01")) %>% 
  ggplot(aes(x = time, y = events, colour = repository_language)) + 
  geom_line() + 
  facet_grid(type ~ repository_language)

github_l %>% 
  filter(time > lubridate::ymd("2013-01-01")) %>% 
  ggplot(aes(x = time, y = events, colour = type)) + 
  geom_line() + 
  facet_grid(. ~ repository_language)

github_l %>% 
  filter(time > lubridate::ymd("2013-01-01")) %>% 
  ggplot(aes(x = time, y = events, fill = type)) + 
  geom_area() + 
  facet_grid(. ~ repository_language)

```

## Coordenadas paralelas

GGplot2 não tem realmente suporte para isso :/

```{r}
github_l %>% 
  filter(time > lubridate::ymd("2013-01-01")) %>% 
  group_by(repository_language, type) %>% 
  summarise(events = mean(events)) %>% 
  ggplot(aes(x = reorder(type, events, FUN = median), 
             y = events, 
             colour = repository_language, 
             group = repository_language)) + 
  geom_point() + 
  geom_line() + 
  xlab("Tipo de evento")

```

Idem. Repare que o pacote ggradar que estou usando tem uma instalação meio chata.

```{r}
#devtools::install_github("ricardo-bion/ggradar", 
#                          dependencies=TRUE)
library(ggradar)
library(scales)

github %>% 
  filter(repository_language %in% c("Scala", "Java", "JavaScript", "Go", "C", "C++")) %>% 
  rename(group = repository_language) %>%
  mutate_each(funs(rescale), -group) %>%
  ggradar()

```


